// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wsaacffjbfkogekquhxr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndzYWFjZmZqYmZrb2dla3F1aHhyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1NzM3MDQsImV4cCI6MjA2NzE0OTcwNH0.soiCxs2HLKBC1Pikjd2rToABnCIFxXmP7K0Hv9l3PxY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});